___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [5]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [9]:
np.identity(3) 
# all values except diagonal elements are zeros
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [16]:
np.random.rand(1)

# argument is to give no of elements of array 
# always it gives between  0 to 1

array([0.56440082])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [22]:

# np.random.seed(45)

print(np.random.randn(25))

[ 1.67029982 -0.49954587  0.67312896  2.24808957 -1.65426275 -0.47439702
 -0.30191524 -0.93102638  1.11098606 -0.18968296  1.27840959 -0.55407712
  0.35430274 -0.44027617 -0.42444883  0.22808162  0.57904417 -0.85418835
 -0.84134033 -0.65570411 -0.1468827  -1.4119755  -0.27055682  1.1293033
 -1.34025807]


#### Create the following matrix:

In [36]:
np.linspace(0.01,1,100).reshape(10,10)

# or

(np.arange(1,101,1)/100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [32]:
#  np.linspace(0,1,20)[1] - np.linspace(0,1,20)[0]
# linearly space means difference between elements are same

np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [43]:
print(mat[(3,4)])

20


20

In [45]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [46]:
mat[4:,:]

array([[21, 22, 23, 24, 25]])

array([21, 22, 23, 24, 25])

In [47]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [49]:
print(np.sum(mat))

325


#### Get the standard deviation of the values in mat

In [50]:
np.std(mat)

np.float64(7.211102550927978)

#### Get the sum of all the columns in mat

In [54]:
print(mat)

# vertical sum of elements
print('_______vertical sum__________________')
print(np.sum(mat, axis=0))
print('_______row wise sum__________________')
print(np.sum(mat, axis=1))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
_______vertical sum__________________
[55 60 65 70 75]
_______row wise sum__________________
[ 15  40  65  90 115]


In [57]:
# How to replace items that satisfy a condition with another value in numpy array?
arr_1d = np.arange(0,11,1)
print(arr_1d)
arr_1d[arr_1d % 2 == 0 ] = -1        # we can not assign array to a str value since it is a int array
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10]
[-1  1 -1  3 -1  5 -1  7 -1  9 -1]


In [63]:
# above scenario the original arrays gets modified
arr_1d = np.arange(0,10,1)
arr_1d_copy = arr_1d.copy()
arr_1d_copy[arr_1d_copy % 2 == 1 ] = -2
print(arr_1d)
print('\n')
print(arr_1d_copy)

# reshaping -1 gives automatically no of cols
arr_1d.reshape(2, -1)

[0 1 2 3 4 5 6 7 8 9]


[ 0 -2  2 -2  4 -2  6 -2  8 -2]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
a = arr_1d.reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
print(a)
print('\n')
print(b)

# vstack to add concatenate arrays vertically
print('\n')

#converts 2d array into 1d array
print(a.flatten())
print('\n')
print(np.vstack([a,b]))
print('\n')
print(np.hstack([a,b]))


[[0 1 2 3 4]
 [5 6 7 8 9]]


[[1 1 1 1 1]
 [1 1 1 1 1]]


[0 1 2 3 4 5 6 7 8 9]


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [89]:
# How to generate custom sequences in numpy without hardcoding?
np.repeat(a, 3)


array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7, 8, 8, 8, 9, 9, 9])

In [104]:
# How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

# can be done without using np using sets
print(list(set(a).intersection(set(b))))

a = np.array(['a','b','c', 1])
b = np.array(['b', 'c', 'd', 'e'])
print(np.intersect1d(a,b))

# to remove elemenst from a which are present in b
# elements are removed from first argument array
print('\n')
print(np.setdiff1d(a,b))
print(np.setdiff1d(b, a))

[2 4]
[np.int64(2), np.int64(4)]
['b' 'c']


['1' 'a']
['d' 'e']


In [126]:

a = np.array([2, 6, 1, 9, 10, 3, 27])
# print([i for i in a if i in range(5,11)])

print(a[(a >= 5) & (a <= 10)])

# also we can use np.where clause
print(np.where((a >= 5) & (a <= 10)))

[ 6  9 10]
(array([1, 3, 4]),)


In [145]:
# comparing elements wise maximum or minimum
a = np.array([5, 7, 9, 8, 6, 4, 5,1])
b = np.array([6, 3, 4, 8, 9, 7, 1,3])

print(np.maximum(a,b))
print('\n')
print(np.minimum(a,b))
print('\n')
print(np.vstack([a,b]))

# compare can happen when arrays are of same length
print('__________________ 2d array compare __________________')
print(np.maximum(a.reshape(2,-1),b.reshape(2,-1)))
print('\n')
print(np.minimum(a.reshape(2,-1),b.reshape(2,-1)))
print('\n')
print(a.reshape(2,-1))
print(b.reshape(2,-1))

[6 7 9 8 9 7 5 3]


[5 3 4 8 6 4 1 1]


[[5 7 9 8 6 4 5 1]
 [6 3 4 8 9 7 1 3]]
__________________ 2d array compare __________________
[[6 7 9 8]
 [9 7 5 3]]


[[5 3 4 8]
 [6 4 1 1]]


[[5 7 9 8]
 [6 4 5 1]]
[[6 3 4 8]
 [9 7 1 3]]


In [179]:
## swapping of two columns , put the postions that you want to swipe
a = np.arange(9).reshape(3,3)
print(a)
print(a[:,[1,0,0]])                            # a[:[indexofcolposition]]
print(a[:,[0,1]])
print('___________________________________')
a[:,[1,2]] = a[:,[2,1]]
print(a)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 0]
 [4 3 3]
 [7 6 6]]
[[0 1]
 [3 4]
 [6 7]]
___________________________________
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [180]:
# reversing rows or array same as used to be in string array
a = np.append(a, [12,13,14]).reshape(4,-1)                             # appending new elements at end of array
print(a)
print('__________reversing a row__________')
print(a[::-1,])
print('___________reversinig columns_________')
print(a[:,::-1])


[[ 0  2  1]
 [ 3  5  4]
 [ 6  8  7]
 [12 13 14]]
__________reversing a row__________
[[12 13 14]
 [ 6  8  7]
 [ 3  5  4]
 [ 0  2  1]]
___________reversinig columns_________
[[ 1  2  0]
 [ 4  5  3]
 [ 7  8  6]
 [14 13 12]]


In [192]:
# Question: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

# Solution:

rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)
print('_______________________rounding off to decimal place _______________________')
print(np.round(rand_arr,decimals=3))



[[6.8243731  9.77448045 8.67007307]
 [9.18554139 6.28115188 9.61573197]
 [5.11404564 8.6363567  7.80192038]
 [9.38876444 6.81543279 8.63370738]
 [6.31436156 9.88216138 8.35443337]]
_______________________rounding off to decimal place _______________________
[[6.824 9.774 8.67 ]
 [9.186 6.281 9.616]
 [5.114 8.636 7.802]
 [9.389 6.815 8.634]
 [6.314 9.882 8.354]]


In [211]:
country_data = np.genfromtxt('rawdata\csv\country.csv', skip_header=1,delimiter=',',usecols = [0,1,2,3], dtype=float)
country_data

array([[    nan, 4.4e+01, 7.2e+04,     nan],
       [    nan, 2.7e+01, 4.8e+04,     nan],
       [    nan, 3.0e+01, 5.4e+04,     nan],
       [    nan, 3.8e+01, 6.1e+04,     nan],
       [    nan, 4.0e+01,     nan,     nan],
       [    nan, 3.5e+01, 5.8e+04,     nan],
       [    nan,     nan, 5.2e+04,     nan],
       [    nan, 4.8e+01, 7.9e+04,     nan],
       [    nan, 5.0e+01, 8.3e+04,     nan],
       [    nan, 3.7e+01, 6.7e+04,     nan]])

In [224]:
np.mean(country_data[:,1:2])

np.float64(nan)

In [223]:
print('Mean age col2 : ', np.mean(country_data[:,1:2]))

Mean age col2 :  nan


In [222]:
country_data[:,1:2].flatten()

array([44., 27., 30., 38., 40., 35., nan, 48., 50., 37.])