___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [8]:
np.identity(3) 
# all values except diagonal elements are zeros
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [9]:
np.random.rand(1)

# argument is to give no of elements of array 
# always it gives between  0 to 1

array([0.1153948])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [10]:

# np.random.seed(45)

print(np.random.randn(25))

[ 1.29230459 -1.92822816 -0.63122802 -0.02200597  1.09276933  0.89403581
 -1.20121308  0.35620668  3.48957122  0.55242253  1.66953584 -1.31318462
 -0.3053776  -0.1851945  -0.97525001  0.69692301  0.90281944 -0.7575564
 -0.98593383 -0.21219342 -1.24111195 -0.81256334  0.02412866 -0.01504609
  1.23857113]


#### Create the following matrix:

In [11]:
np.linspace(0.01,1,100).reshape(10,10)

# or

(np.arange(1,101,1)/100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
#  np.linspace(0,1,20)[1] - np.linspace(0,1,20)[0]
# linearly space means difference between elements are same

np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
print(mat[(3,4)])

20


In [16]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [17]:
mat[4:,:]

array([[21, 22, 23, 24, 25]])

In [18]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [19]:
print(np.sum(mat))

325


#### Get the standard deviation of the values in mat

In [20]:
np.std(mat)

np.float64(7.211102550927978)

#### Get the sum of all the columns in mat

In [21]:
print(mat)

# vertical sum of elements
print('_______vertical sum__________________')
print(np.sum(mat, axis=0))
print('_______row wise sum__________________')
print(np.sum(mat, axis=1))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
_______vertical sum__________________
[55 60 65 70 75]
_______row wise sum__________________
[ 15  40  65  90 115]


In [22]:
# How to replace items that satisfy a condition with another value in numpy array?
arr_1d = np.arange(0,11,1)
print(arr_1d)
arr_1d[arr_1d % 2 == 0 ] = -1        # we can not assign array to a str value since it is a int array
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10]
[-1  1 -1  3 -1  5 -1  7 -1  9 -1]


In [23]:
# above scenario the original arrays gets modified
arr_1d = np.arange(0,10,1)
arr_1d_copy = arr_1d.copy()
arr_1d_copy[arr_1d_copy % 2 == 1 ] = -2
print(arr_1d)
print('\n')
print(arr_1d_copy)

# reshaping -1 gives automatically no of cols
arr_1d.reshape(2, -1)

[0 1 2 3 4 5 6 7 8 9]


[ 0 -2  2 -2  4 -2  6 -2  8 -2]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
a = arr_1d.reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
print(a)
print('\n')
print(b)

# vstack to add concatenate arrays vertically
print('\n')

#converts 2d array into 1d array
print(a.flatten())
print('\n')
print(np.vstack([a,b]))
print('\n')
print(np.hstack([a,b]))


[[0 1 2 3 4]
 [5 6 7 8 9]]


[[1 1 1 1 1]
 [1 1 1 1 1]]


[0 1 2 3 4 5 6 7 8 9]


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [25]:
# How to generate custom sequences in numpy without hardcoding?
np.repeat(a, 3)


array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7, 8, 8, 8, 9, 9, 9])

In [26]:
# How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

# can be done without using np using sets
print(list(set(a).intersection(set(b))))

a = np.array(['a','b','c', 1])
b = np.array(['b', 'c', 'd', 'e'])
print(np.intersect1d(a,b))

# to remove elemenst from a which are present in b
# elements are removed from first argument array
print('\n')
print(np.setdiff1d(a,b))
print(np.setdiff1d(b, a))

[2 4]
[np.int64(2), np.int64(4)]
['b' 'c']


['1' 'a']
['d' 'e']


In [27]:

a = np.array([2, 6, 1, 9, 10, 3, 27])
# print([i for i in a if i in range(5,11)])

print(a[(a >= 5) & (a <= 10)])

# also we can use np.where clause
print(np.where((a >= 5) & (a <= 10)))

[ 6  9 10]
(array([1, 3, 4]),)


In [28]:
# comparing elements wise maximum or minimum
a = np.array([5, 7, 9, 8, 6, 4, 5,1])
b = np.array([6, 3, 4, 8, 9, 7, 1,3])

print(np.maximum(a,b))
print('\n')
print(np.minimum(a,b))
print('\n')
print(np.vstack([a,b]))

# compare can happen when arrays are of same length
print('__________________ 2d array compare __________________')
print(np.maximum(a.reshape(2,-1),b.reshape(2,-1)))
print('\n')
print(np.minimum(a.reshape(2,-1),b.reshape(2,-1)))
print('\n')
print(a.reshape(2,-1))
print(b.reshape(2,-1))

[6 7 9 8 9 7 5 3]


[5 3 4 8 6 4 1 1]


[[5 7 9 8 6 4 5 1]
 [6 3 4 8 9 7 1 3]]
__________________ 2d array compare __________________
[[6 7 9 8]
 [9 7 5 3]]


[[5 3 4 8]
 [6 4 1 1]]


[[5 7 9 8]
 [6 4 5 1]]
[[6 3 4 8]
 [9 7 1 3]]


In [29]:
## swapping of two columns , put the postions that you want to swipe
a = np.arange(9).reshape(3,3)
print(a)
print(a[:,[1,0,0]])                            # a[:[indexofcolposition]]
print(a[:,[0,1]])
print('___________________________________')
a[:,[1,2]] = a[:,[2,1]]
print(a)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 0]
 [4 3 3]
 [7 6 6]]
[[0 1]
 [3 4]
 [6 7]]
___________________________________
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [30]:
# reversing rows or array same as used to be in string array
a = np.append(a, [12,13,14]).reshape(4,-1)                             # appending new elements at end of array
print(a)
print('__________reversing a row__________')
print(a[::-1,])
print('___________reversinig columns_________')
print(a[:,::-1])


[[ 0  2  1]
 [ 3  5  4]
 [ 6  8  7]
 [12 13 14]]
__________reversing a row__________
[[12 13 14]
 [ 6  8  7]
 [ 3  5  4]
 [ 0  2  1]]
___________reversinig columns_________
[[ 1  2  0]
 [ 4  5  3]
 [ 7  8  6]
 [14 13 12]]


In [31]:
# Question: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

# Solution:

rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)
print('_______________________rounding off to decimal place _______________________')
print(np.round(rand_arr,decimals=3))



[[6.02361942 9.02941867 5.21345697]
 [8.01720791 6.04831258 8.49163953]
 [7.16193894 6.41010817 6.68494516]
 [5.92402681 7.44473211 6.49153949]
 [8.22524027 5.7137889  7.54592054]]
_______________________rounding off to decimal place _______________________
[[6.024 9.029 5.213]
 [8.017 6.048 8.492]
 [7.162 6.41  6.685]
 [5.924 7.445 6.492]
 [8.225 5.714 7.546]]


In [32]:
country_data = np.genfromtxt('rawdata\csv\country.csv', skip_header=1,delimiter=',',usecols = [0,1,2,3], dtype=float)
country_data

array([[    nan, 4.4e+01, 7.2e+04,     nan],
       [    nan, 2.7e+01, 4.8e+04,     nan],
       [    nan, 3.0e+01, 5.4e+04,     nan],
       [    nan, 3.8e+01, 6.1e+04,     nan],
       [    nan, 4.0e+01,     nan,     nan],
       [    nan, 3.5e+01, 5.8e+04,     nan],
       [    nan,     nan, 5.2e+04,     nan],
       [    nan, 4.8e+01, 7.9e+04,     nan],
       [    nan, 5.0e+01, 8.3e+04,     nan],
       [    nan, 3.7e+01, 6.7e+04,     nan]])

In [36]:
np.mean(country_data[:,1:2])

np.float64(38.9)

In [41]:
#mean does not works when there is any 'nan' or missing value in data
# so first i have removed nan to some value
country_data[6:7,1:2] = 40 
print('Mean age col2 : ', np.mean(country_data[:,1:2]))

print('Median age of col2 : ', np.median(country_data[:,1:2]))

print('Standard Deviation of col2 :', np.std(country_data[:,1:2]))

print(country_data[:,1:2])

# read maths for meadian and standard deviation ????????????????

Mean age col2 :  38.9
Median age of col2 :  39.0
Standard Deviation of col2 : 6.89129886160802
[[44.]
 [27.]
 [30.]
 [38.]
 [40.]
 [35.]
 [40.]
 [48.]
 [50.]
 [37.]]


numpy.set_printoptions
numpy.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, *, legacy=None, override_repr=None)[source]
Set printing options.

These options determine the way floating point numbers, arrays and other NumPy objects are displayed.

Parameters:
precisionint or None, optional
Number of digits of precision for floating point output (default 8). May be None if floatmode is not fixed, to print as many digits as necessary to uniquely specify the value.

thresholdint, optional
Total number of array elements which trigger summarization rather than full repr (default 1000). To always use the full repr without summarization, pass sys.maxsize.

edgeitemsint, optional
Number of array items in summary at beginning and end of each dimension (default 3).

linewidthint, optional
The number of characters per line for the purpose of inserting line breaks (default 75).

suppressbool, optional
If True, always print floating point numbers using fixed point notation, in which case numbers equal to zero in the current precision will print as zero. If False, then scientific notation is used when absolute value of the smallest number is < 1e-4 or the ratio of the maximum absolute value to the minimum is > 1e3. The default is False.

nanstrstr, optional
String representation of floating point not-a-number (default nan).

infstrstr, optional
String representation of floating point infinity (default inf).

signstring, either ‘-’, ‘+’, or ‘ ‘, optional
Controls printing of the sign of floating-point types. If ‘+’, always print the sign of positive values. If ‘ ‘, always prints a space (whitespace character) in the sign position of positive values. If ‘-’, omit the sign character of positive values. (default ‘-‘)

In [42]:
# percentile 


In [52]:
# inserting random values at random positions of array
country_data = np.genfromtxt('rawdata\csv\country.csv', skip_header=1,delimiter=',',usecols = [0,1,2,3], dtype=object)

print(country_data)
print('\n')

for i in (np.random.randint(0, len(country_data), 5)):
    country_data[i] = 'nval'
print(country_data)

# find positions where nan is there

np.isnan(country_data).sum()

[[b'France' b'44' b'72000' b'Yes']
 [b'Spain' b'27' b'48000' b'Yes']
 [b'' b'30' b'54000' b'']
 [b'Spain' b'38' b'61000' b'No']
 [b'Germany' b'40' b'' b'Yes']
 [b'France' b'35' b'58000' b'Yes']
 [b'Spain' b'' b'52000' b'No']
 [b'France' b'48' b'79000' b'Yes']
 [b'Germany' b'50' b'83000' b'No']
 [b'France' b'37' b'67000' b'Yes']]


[[b'France' b'44' b'72000' b'Yes']
 [b'Spain' b'27' b'48000' b'Yes']
 [b'' b'30' b'54000' b'']
 ['nval' 'nval' 'nval' 'nval']
 [b'Germany' b'40' b'' b'Yes']
 ['nval' 'nval' 'nval' 'nval']
 ['nval' 'nval' 'nval' 'nval']
 ['nval' 'nval' 'nval' 'nval']
 ['nval' 'nval' 'nval' 'nval']
 [b'France' b'37' b'67000' b'Yes']]


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [53]:
# start from question 34 of kaggle numpy exercise