In [1]:
import pandas

In [2]:
! pip install pandas

You should consider upgrading via the 'C:\Users\ashpi\DataEngMain\projects\basics\pr-venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [3]:
! pip install scikit-learn

You should consider upgrading via the 'C:\Users\ashpi\DataEngMain\projects\basics\pr-venv\Scripts\python.exe -m pip install --upgrade pip' command.


## imports

In [4]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

## numpy udemy

In [61]:
# similar to range function in normal python
print(np.arange(1,11,2))                         #<-- one dimensional array
lst = [i for i in 'ashishkumar']
lst2= [i for i in 'dwivediakd1']

data = np.array([lst, lst, lst2])                #<-- passing list of list in array , will give 2-d array
print(data)                                      # two brackets

print('________________________CREATE SAMPLE NP ARRAYS_______________________________________________')
ones = np.ones((2,3))                              # takes no of rows and cols i tuple, put one argument will give 
ones_1d = np.ones(5)                               # 1d array
print(ones_1d)
print(ones)

np.random.randint(1,10,5)            # 5 is no of elements that i want to generate randomly

[1 3 5 7 9]
[['a' 's' 'h' 'i' 's' 'h' 'k' 'u' 'm' 'a' 'r']
 ['a' 's' 'h' 'i' 's' 'h' 'k' 'u' 'm' 'a' 'r']
 ['d' 'w' 'i' 'v' 'e' 'd' 'i' 'a' 'k' 'd' '1']]
________________________CREATE SAMPLE NP ARRAYS_______________________________________________
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


array([2, 9, 1, 3, 7], dtype=int32)

The linspace() method of the NumPy library is a useful tool to generate sequences of data points. It is also used in data visualization.
The NumPy.linspace() function returns an array of evenly spaced values within the specified interval [start, stop].

It is similar to NumPy.arange() function but instead of a step, it uses a sample number. 

In [50]:
# start , stop, no of elements
print(np.linspace(1,10,10))
# during analysis we can use generated np array to do some mathematical operation
print(np.square(np.linspace(1,10,10)))

#other ways to genarate random array
print(np.random.rand(5,5))
print(np.random.randn(5,5))
#to get single random between low and high
print(np.random.randint(1,5))

# to get multiple nos between low and high
rand_int_ary = np.random.randint(1,100,20)
print(np.random.randint(1,100,10))
# for i in rand_int_ary:
#     print(i)
rand_int_ary[2]

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]
[[0.40936766 0.06634488 0.09841441 0.49615731 0.67380731]
 [0.54667847 0.04702988 0.42825126 0.21073398 0.43920617]
 [0.60941268 0.09528854 0.48176246 0.25350504 0.75510595]
 [0.15069064 0.18706767 0.60527249 0.90133133 0.67557529]
 [0.47990878 0.32431884 0.55432178 0.32374896 0.535456  ]]
[[ 0.39385175 -2.21757793 -0.27195432 -1.47181095  1.24211197]
 [-0.52590516 -0.34147839 -0.35939881  1.04643442 -0.3259297 ]
 [-0.09097694 -0.45311188 -0.2907892   0.3704332   0.3756728 ]
 [-0.25830134  1.05857807  1.17907123 -0.01111536  0.04955758]
 [ 0.45350247 -0.38230868 -1.43535304 -0.32024538  0.81952028]]
1
[52 87 89 48 69 72 78 44 30  5]


np.int32(19)

In [60]:
# to know the shape of an array use shape 
# shape is an attribute not function 
print('shape of rand_int_ary is :', rand_int_ary.shape)
print('shape of data array is :', data.shape)
print('max value of array is : ', rand_int_ary.max(), 'index of max value is : ',rand_int_ary.argmax())
# reshaping of array
# we can reshapre from 1d to 2d but rows * cols must be equal to no of all elements of array
print(rand_int_ary)
print(rand_int_ary.reshape(2,10))
print(rand_int_ary.reshape(4,5))

shape of rand_int_ary is : (20,)
shape of data array is : (3, 11)
max value of array is :  99 index of max value is :  11
[63 36 19 74 86 54 34  4 39 42 39 99 25 74 26 65 35 10 18 55]
[[63 36 19 74 86 54 34  4 39 42]
 [39 99 25 74 26 65 35 10 18 55]]
[[63 36 19 74 86]
 [54 34  4 39 42]
 [39 99 25 74 26]
 [65 35 10 18 55]]


In [6]:
# data = {'Name':['Tom', 'nick', 'krish', 'jack'],
#         'Age':[20, 21, 19]}
# above dict data will throw error due to mismatch or array
# --> ValueError: All arrays must be of the same length
data = [{'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19,24]},
        {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19,24]},
        {'Name':['Ashish', 'Piyush', 'AD', 'PD'],
        'Age':[20, 21, 19,24]},
        {'Namee':['Tom', 'nick', 'krish', 'jack'], #dataframe will insert NaN when any key is missing from dict of list
        'Ageee':[20, 21, 19,24]}]
df = pd.DataFrame(data)
print(df)
print('________________________________________________________________')
data1 = {{'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19,24]},
        {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19,24]},
        {'Name':['Ashish', 'Ramesh', 'Ram', 'AD'],
        'Age':[20, 21, 19,24]},
        {'Name':['Tom', 'nick', 'krish', 'jack'], 
        'Age':[20, 21, 19,24]}}
df = pd.DataFrame(data1)
print(df)

                       Name               Age                     Namee  \
0  [Tom, nick, krish, jack]  [20, 21, 19, 24]                       NaN   
1  [Tom, nick, krish, jack]  [20, 21, 19, 24]                       NaN   
2  [Ashish, Piyush, AD, PD]  [20, 21, 19, 24]                       NaN   
3                       NaN               NaN  [Tom, nick, krish, jack]   

              Ageee  
0               NaN  
1               NaN  
2               NaN  
3  [20, 21, 19, 24]  
________________________________________________________________


TypeError: unhashable type: 'dict'

## Reading a CSV File

In [7]:

#csv_data = pd.read_csv(r'C:\Users\ashpi\DataEngMain\projects\basics\rawdata\csv\googleplaystore.csv')

#above is full path read , below is relative path
csv_data = pd.read_csv('rawdata\csv\googleplaystore.csv')
## get top 5 data
top_10 = csv_data.head(10)

print(csv_data.columns)
print('______________________________________________________________________________________________')

# to get any column data specify the index name
print(top_10['App'])
print('length of top 10 data frame -->', len(top_10['App']))
print('______________________________________________________________________________________________')
print(len(csv_data['Rating']))

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')
______________________________________________________________________________________________
0       Photo Editor & Candy Camera & Grid & ScrapBook
1                                  Coloring book moana
2    U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                Sketch - Draw & Paint
4                Pixel Draw - Number Art Coloring Book
5                           Paper flowers instructions
6              Smoke Effect Photo Maker - Smoke Editor
7                                     Infinite Painter
8                                 Garden Coloring Book
9                        Kids Paint Free - Drawing Fun
Name: App, dtype: object
length of top 10 data frame --> 10
______________________________________________________________________________________________
10841

In [8]:
print('to check total field if having -->', csv_data.isnull().sum())

# to check if column 'current Ver' has any null values or not 
print('to check any particular column -->',csv_data['Current Ver'].isnull().sum())

# to check if any duplicates is there in any column, multiple columns can also be given
csv_data['App'].duplicated()

# to get unique values from a column
type(csv_data['Category'].unique())
for i in csv_data['Category'].unique():
    print(i)

to check total field if having --> App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64
to check any particular column --> 8
ART_AND_DESIGN
AUTO_AND_VEHICLES
BEAUTY
BOOKS_AND_REFERENCE
BUSINESS
COMICS
COMMUNICATION
DATING
EDUCATION
ENTERTAINMENT
EVENTS
FINANCE
FOOD_AND_DRINK
HEALTH_AND_FITNESS
HOUSE_AND_HOME
LIBRARIES_AND_DEMO
LIFESTYLE
GAME
FAMILY
MEDICAL
SOCIAL
SHOPPING
PHOTOGRAPHY
SPORTS
TRAVEL_AND_LOCAL
TOOLS
PERSONALIZATION
PRODUCTIVITY
PARENTING
WEATHER
VIDEO_PLAYERS
NEWS_AND_MAGAZINES
MAPS_AND_NAVIGATION
1.9


In [9]:
# dropping rows from dataframe which having NaN
csv_data.dropna()

# to fill values having NaN with some default value , since we can not remove whole data if a single column
# entry is null

fillna_csv_data = csv_data.fillna(4.5)
fillna_csv_data.isnull().sum()  #<-- sum of nan  values by each column
# we should always fill data based on column names , since every column has some different value
# so fill data based on column values
fill_rating = csv_data.fillna({'Rating': 4.5})
## above command only fills rating column , to add more columns we can add multiple dict column value pairs
print(fill_rating.isnull().sum())

## describe tells us about column details
print('_____________________________________________________________________________________________________')
print(csv_data['Category'].describe())

#Counting occurance of a value in table
print(csv_data['Category'].value_counts().get('FAMILY', 0))

print((csv_data['Category'] == 'FAMILY').sum())

print('______________occurnace of each value in a column_______________')
for cat in csv_data['Category'].unique():
    print(cat , ":", csv_data['Category'].value_counts().get(cat, 0))

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    1
Genres            0
Last Updated      0
Current Ver       8
Android Ver       3
dtype: int64
_____________________________________________________________________________________________________
count      10841
unique        34
top       FAMILY
freq        1972
Name: Category, dtype: object
1972
1972
______________occurnace of each value in a column_______________
ART_AND_DESIGN : 65
AUTO_AND_VEHICLES : 85
BEAUTY : 53
BOOKS_AND_REFERENCE : 231
BUSINESS : 460
COMICS : 60
COMMUNICATION : 387
DATING : 234
EDUCATION : 156
ENTERTAINMENT : 149
EVENTS : 64
FINANCE : 366
FOOD_AND_DRINK : 127
HEALTH_AND_FITNESS : 341
HOUSE_AND_HOME : 88
LIBRARIES_AND_DEMO : 85
LIFESTYLE : 382
GAME : 1144
FAMILY : 1972
MEDICAL : 463
SOCIAL : 295
SHOPPING : 260
PHOTOGRAPHY : 335
SPORTS : 384
TRAVEL_AND_LOCAL : 258
TOOLS : 843
PERSONALI

In [10]:
csv_data.tail(5)

App             Category  \
10836                               Sya9a Maroc - FR               FAMILY   
10837               Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                         Parkinson Exercices FR              MEDICAL   
10839                  The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840  iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews                Size     Installs  Type Price  \
10836     4.5      38                 53M       5,000+  Free     0   
10837     5.0       4                3.6M         100+  Free     0   
10838     NaN       3                9.5M       1,000+  Free     0   
10839     4.5     114  Varies with device       1,000+  Free     0   
10840     4.5  398307                 19M  10,000,000+  Free     0   

      Content Rating             Genres      Last Updated         Current Ver  \
10836       Everyone          Education     July 25, 2017                1.48   
10837       Everyone          Education      July 6, 2018                 1.0   
10838       Everyone            Medical  January 20, 2017                 1.0   
10839     Mature 17+  Books & Reference  January 19, 2015  Varies with device   
10840       Everyone          Lifestyle     July 25, 2018  Varies with device   

              Android Ver  
10836          4.1 and up  
10837          4.1 and up  
10838          2.2 and up  
10839  Varies with device  
10840  Varies with device

In [11]:
d1 = pd.DataFrame([[1,2,3], [1,2,3], ['a','b','c']])
d1

0  1  2
0  1  2  3
1  1  2  3
2  a  b  c

## filling values with sklearn imputer

In [13]:
country_csv = pd.read_csv('rawdata\csv\country.csv')
print(country_csv)

   Country   Age   Salary Purchased
0   France  44.0  72000.0       Yes
1    Spain  27.0  48000.0       Yes
2      NaN  30.0  54000.0       NaN
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [14]:
#check isnull from above data set
country_csv.isnull().sum()

Country      1
Age          1
Salary       1
Purchased    1
dtype: int64

In [15]:
#iloc slicing - very similar to slicing 
# df.iloc[start_row : end_row, start_col : end:col]
country_csv.iloc[:,1:2]

Age
0  44.0
1  27.0
2  30.0
3  38.0
4  40.0
5  35.0
6   NaN
7  48.0
8  50.0
9  37.0

In [16]:
# updating age column from above date frame

imp_mean = SimpleImputer(missing_values= np.nan, strategy= 'mean')
imp_mean.fit(country_csv.iloc[:,1:2])

#receiveing transformed values
country_csv.iloc[:,1:2] = imp_mean.transform(country_csv.iloc[:,1:2])

# now updated salary column with same mean strategy 
imp_mean.fit(country_csv.iloc[:,2:3])
country_csv.iloc[:,2:3] = imp_mean.transform(country_csv.iloc[:,2:3])

# updating nan in categorical data using most frequent
imp_mostfreq = SimpleImputer(missing_values= np.nan, strategy='most_frequent')
country_csv.iloc[:,:1] = imp_mostfreq.fit_transform(country_csv.iloc[:,:1])
# same strategy for purchased
country_csv.iloc[:,3:4] = imp_mostfreq.fit_transform(country_csv.iloc[:,3:4])
country_csv

Country        Age        Salary Purchased
0   France  44.000000  72000.000000       Yes
1    Spain  27.000000  48000.000000       Yes
2   France  30.000000  54000.000000       Yes
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [17]:
country_csv.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [18]:
csv_data.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [19]:
csv_data.iloc[:, 2:3] = imp_mean.fit_transform(csv_data.iloc[:, 2:3])

In [20]:
# after rating is converted with nan to mean 
# lets drop some rows these are not much weightage so we can drop
csv_data = csv_data.dropna()   #<-- drops nan rows and updates the dataframe 

print(csv_data.isnull().sum())

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64


In [21]:
# df.sample() give random samples from whole df, we shoud use instead of df.head(), df.tail() gives 5 rows
print(csv_data.sample(5))
print('______________________________df.info() gives column types  ___________________________________________')
print(csv_data.info())
print(country_csv.info())
print("_______________shape gives no of rows and columns __________________________")
print('no of rows and cols in country', country_csv.shape)
print('no of rows and cols in csv data dataframe ', csv_data.shape)
print('____________________df.describe()___________________________________________')
# Description: Computes summary statistics (count, mean, std, min, 25%, 50%, 75%, max) for numerical columns in DataFrame df.
print(country_csv.describe())
print(csv_data.describe())

                               App            Category    Rating Reviews  \
7472                     CK SKILLZ  HEALTH_AND_FITNESS  4.193338       0   
5866  iMediaShare – Photos & Music       VIDEO_PLAYERS  4.200000  104551   
7482                    Tic Tac CK              FAMILY  5.000000       3   
1816                Merge Dragons!                GAME  4.500000  214777   
7063                TFO BZ Lessons              FAMILY  4.400000      75   

      Size     Installs  Type Price Content Rating                   Genres  \
7472  8.6M          50+  Free     0       Everyone         Health & Fitness   
5866   18M  10,000,000+  Free     0       Everyone  Video Players & Editors   
7482   13M          10+  Free     0       Everyone                   Puzzle   
1816   91M   5,000,000+  Free     0       Everyone                   Puzzle   
7063  3.7M         500+  Free     0       Everyone                Education   

           Last Updated Current Ver   Android Ver  
7472       May 1