In [3]:
! pip install pandas

You should consider upgrading via the 'C:\Users\ashpi\DataEngMain\projects\basics\pr-venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [4]:
! pip install scikit-learn

You should consider upgrading via the 'C:\Users\ashpi\DataEngMain\projects\basics\pr-venv\Scripts\python.exe -m pip install --upgrade pip' command.


## imports

In [2]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

## numpy udemy

In [3]:
# similar to range function in normal python
print(np.arange(1,11,2))                         #<-- one dimensional array
print('_______ Two dimensional matrix __________________')
lst = [i for i in 'ashishkumar']
lst2= [i for i in 'dwivediakd1']

data = np.array([lst, lst, lst2])                #<-- passing list of list in array , will give 2-d array
print(data)                                      # two brackets

print('________________________CREATE SAMPLE NP ARRAYS_______________________________________________')
ones = np.ones((2,3))                              # takes no of rows and cols i tuple, put one argument will give 
ones_1d = np.ones(5)                               # 1d array
print(ones_1d)
print(ones)

np.random.randint(1,10,5)            # 5 is no of elements that i want to generate randomly

[1 3 5 7 9]
_______ Two dimensional matrix __________________
[['a' 's' 'h' 'i' 's' 'h' 'k' 'u' 'm' 'a' 'r']
 ['a' 's' 'h' 'i' 's' 'h' 'k' 'u' 'm' 'a' 'r']
 ['d' 'w' 'i' 'v' 'e' 'd' 'i' 'a' 'k' 'd' '1']]
________________________CREATE SAMPLE NP ARRAYS_______________________________________________
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


array([9, 4, 6, 5, 2], dtype=int32)

In [24]:
print(data)

# to get rows use index data[0]
# to get rows use slicing  data[start_row, end_row : start_col, end_col ]
print(data[: ,(0,1,2)])
print('______________________________________________________')
df = pd.DataFrame(data, columns=['c10', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c88', 'c9', 'c10', 'c11'])
print(df)

[['a' 's' 'h' 'i' 's' 'h' 'k' 'u' 'm' 'a' 'r']
 ['a' 's' 'h' 'i' 's' 'h' 'k' 'u' 'm' 'a' 'r']
 ['d' 'w' 'i' 'v' 'e' 'd' 'i' 'a' 'k' 'd' '1']]
[['a' 's' 'h']
 ['a' 's' 'h']
 ['d' 'w' 'i']]
______________________________________________________
  c10 c2 c3 c4 c5 c6 c7 c88 c9 c10 c11
0   a  s  h  i  s  h  k   u  m   a   r
1   a  s  h  i  s  h  k   u  m   a   r
2   d  w  i  v  e  d  i   a  k   d   1


The linspace() method of the NumPy library is a useful tool to generate sequences of data points. It is also used in data visualization.
The NumPy.linspace() function returns an array of evenly spaced values within the specified interval [start, stop].

It is similar to NumPy.arange() function but instead of a step, it uses a sample number. 

In [29]:
# start , stop, no of elements
print(np.linspace(1,10,30))
print('______________________________________________________')
# during analysis we can use generated np array to do some mathematical operation
print(np.square(np.linspace(1,10,10)))
print('______________________________________________________')
#other ways to genarate random array between 0 to 1
print(np.random.rand(5,5))
print('\n')
print(np.random.randn(5,5))
#to get single random between low and high
print('______________________ random integer________________________________')
print(np.random.randint(1,5))

# to get multiple nos between low and high
rand_int_ary = np.random.randint(1,100,20)
print(np.random.randint(1,100,10))
# for i in rand_int_ary:
#     print(i)
rand_int_ary[2]

[ 1.          1.31034483  1.62068966  1.93103448  2.24137931  2.55172414
  2.86206897  3.17241379  3.48275862  3.79310345  4.10344828  4.4137931
  4.72413793  5.03448276  5.34482759  5.65517241  5.96551724  6.27586207
  6.5862069   6.89655172  7.20689655  7.51724138  7.82758621  8.13793103
  8.44827586  8.75862069  9.06896552  9.37931034  9.68965517 10.        ]
______________________________________________________
[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]
______________________________________________________
[[0.09606574 0.18001035 0.71990336 0.9495309  0.83631543]
 [0.53680916 0.07697076 0.05134272 0.05124925 0.42978621]
 [0.9776895  0.02063697 0.03057742 0.13354716 0.52509849]
 [0.37576762 0.42104623 0.64757307 0.35448597 0.83523996]
 [0.67536269 0.91683957 0.67696192 0.7520602  0.67048118]]


[[-1.39031632 -0.56837339 -0.82679044  0.1785438  -1.24390902]
 [-1.0843845  -0.66322613  1.50630689  0.33992055 -0.71205479]
 [-1.22068337 -0.84727414  1.6835646  -0.47074783 -0.6

np.int32(10)

In [30]:
print(rand_int_ary)
print('______________________________________________________')
print(data)
# to know the shape of an array use shape 
# shape is an attribute not function 
print('______________________________________________________')
print('shape of rand_int_ary is :', rand_int_ary.shape)
print('____________________ shape of data array __________________________________')
print('shape of data array is :', data.shape)
print('______________________________________________________')
print('max value of array is : ', rand_int_ary.max(), 'index of max value is : ',rand_int_ary.argmax())
# reshaping of array
# we can reshapre from 1d to 2d but rows * cols must be equal to no of all elements of array
print('\n')
print(rand_int_ary)
print(rand_int_ary.reshape(2,10))
print(rand_int_ary.reshape(4,5))

[26 82 10 92 75 91 19 90 72  5 93 51 30 90  5 42 96  9 54 13]
______________________________________________________
[['a' 's' 'h' 'i' 's' 'h' 'k' 'u' 'm' 'a' 'r']
 ['a' 's' 'h' 'i' 's' 'h' 'k' 'u' 'm' 'a' 'r']
 ['d' 'w' 'i' 'v' 'e' 'd' 'i' 'a' 'k' 'd' '1']]
______________________________________________________
shape of rand_int_ary is : (20,)
____________________ shape of data array __________________________________
shape of data array is : (3, 11)
______________________________________________________
max value of array is :  96 index of max value is :  16


[26 82 10 92 75 91 19 90 72  5 93 51 30 90  5 42 96  9 54 13]
[[26 82 10 92 75 91 19 90 72  5]
 [93 51 30 90  5 42 96  9 54 13]]
[[26 82 10 92 75]
 [91 19 90 72  5]
 [93 51 30 90  5]
 [42 96  9 54 13]]


# shorting numpy array

In [48]:
print(np.sort(rand_int_ary))
print(rand_int_ary.mean())
print(rand_int_ary.std())
print(np.median(rand_int_ary))

arr = [[14, 17, 12, 33, 44],   
       [15, 6, 27, 8, 19],  
       [23, 2, 54, 1, 4, ]] 
print('____________________ sorting 2D arrays________________________')
print(np.sort(arr))
print('__________________ row wise average____________________________')
print(np.mean(arr, axis=0))
print('__________________ column wise average____________________________')
print(np.mean(arr, axis=1))
print('________________ median middle value for odd nos ______________________________')
print(np.median(arr, axis= 0))
print('___________________________________________________________')
print(np.median(arr, axis= 1))

[ 5  5  9 10 13 19 26 30 42 51 54 72 75 82 90 90 91 92 93 96]
52.25
34.17583210398834
52.5
____________________ sorting 2D arrays________________________
[[12 14 17 33 44]
 [ 6  8 15 19 27]
 [ 1  2  4 23 54]]
__________________ row wise average____________________________
[17.33333333  8.33333333 31.         14.         22.33333333]
__________________ column wise average____________________________
[24.  15.  16.8]
________________ median middle value for odd nos ______________________________
[15.  6. 27.  8. 19.]
___________________________________________________________
[17. 15.  4.]


# converting numpy array to dataframe

In [10]:
print(pd.DataFrame(rand_int_ary))
print('\n')
print(pd.DataFrame(rand_int_ary.reshape(2,10)))
print('\n')
print(pd.DataFrame(rand_int_ary.reshape(4,5)))
print('\n')
print(pd.DataFrame(rand_int_ary.reshape(4,5), index=['a', 'b', 'c', 'd'], columns={'c1': 'A', 'c2': 'B', 'c3': 'C', 'c4': 'D', 'c5': 'E'}))

     0
0   90
1   57
2   80
3    9
4   62
5   84
6   71
7   84
8   46
9   22
10  83
11  25
12  20
13  66
14  15
15  73
16  11
17  92
18  25
19  89


    0   1   2   3   4   5   6   7   8   9
0  90  57  80   9  62  84  71  84  46  22
1  83  25  20  66  15  73  11  92  25  89


    0   1   2   3   4
0  90  57  80   9  62
1  84  71  84  46  22
2  83  25  20  66  15
3  73  11  92  25  89


   c1  c2  c3  c4  c5
a  90  57  80   9  62
b  84  71  84  46  22
c  83  25  20  66  15
d  73  11  92  25  89


In [53]:
# data = {'Name':['Tom', 'nick', 'krish', 'jack'],
#         'Age':[20, 21, 19]}
# above dict data will throw error due to mismatch or array
# --> ValueError: All arrays must be of the same length
data = [{'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19,24]},
        {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19,24]},
        {'Name':['Ashish', 'Piyush', 'AD', 'PD'],
        'Age':[20, 21, 19,24]},
        {'Namee':['Tom', 'nick', 'krish', 'jack'], #dataframe will insert NaN when any key is missing from dict of list
        'Age':[20, 21, 19,24]}]
df = pd.DataFrame(data)
print(df)
print('_________________ above considers all keys as col name_______________________________________________')
# data1 = {{'Name':['Tom', 'nick', 'krish', 'jack'],
#         'Age':[20, 21, 19,24]},
#         {'Name':['Tom', 'nick', 'krish', 'jack'],
#         'Age':[20, 21, 19,24]},
#         {'Name':['Ashish', 'Ramesh', 'Ram', 'AD'],
#         'Age':[20, 21, 19,24]},
#         {'Name':['Tom', 'nick', 'krish', 'jack'], 
#         'Age':[20, 21, 19,24]}}
# df = pd.DataFrame(data1)
# print(df)

                       Name               Age                     Namee
0  [Tom, nick, krish, jack]  [20, 21, 19, 24]                       NaN
1  [Tom, nick, krish, jack]  [20, 21, 19, 24]                       NaN
2  [Ashish, Piyush, AD, PD]  [20, 21, 19, 24]                       NaN
3                       NaN  [20, 21, 19, 24]  [Tom, nick, krish, jack]
_________________ above considers all keys as col name_______________________________________________


## Reading a CSV File

In [59]:

#csv_data = pd.read_csv(r'C:\Users\ashpi\DataEngMain\projects\basics\rawdata\csv\googleplaystore.csv')

#above is full path read , below is relative path
csv_data = pd.read_csv('rawdata\csv\googleplaystore.csv')
## get top 5 data
top_10 = csv_data.head(10)
print(type(csv_data))         ## once we read a csv file using pandas it generates ddatframe
print(csv_data.columns)
print('______________________________________________________________________________________________')

# to get any column data specify the index name for single column just pass col name
# to get multiple pass list of cols ['App', 'Rating']
print(top_10[['App', 'Rating']])
print('______________________________________________________________________________________________')
print('length of top 10 data frame -->', len(top_10['App']))
print('______________________________________________________________________________________________')
print(len(csv_data['Rating']))

<class 'pandas.core.frame.DataFrame'>
Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')
______________________________________________________________________________________________
                                                 App  Rating
0     Photo Editor & Candy Camera & Grid & ScrapBook     4.1
1                                Coloring book moana     3.9
2  U Launcher Lite – FREE Live Cool Themes, Hide ...     4.7
3                              Sketch - Draw & Paint     4.5
4              Pixel Draw - Number Art Coloring Book     4.3
5                         Paper flowers instructions     4.4
6            Smoke Effect Photo Maker - Smoke Editor     3.8
7                                   Infinite Painter     4.1
8                               Garden Coloring Book     4.4
9                      Kids Paint Free - Drawing Fun     4.7
_

In [60]:
print('to check total field if having -->', csv_data.isnull().sum())

# to check if column 'current Ver' has any null values or not 
print('to check any particular column -->',csv_data['Current Ver'].isnull().sum())
print('______________________________________________________________________________________________')
# to check if any duplicates is there in any column, multiple columns can also be given
csv_data['App'].duplicated()
print('______________________________________________________________________________________________')
print(csv_data[csv_data.duplicated(keep=False)])     # keep false gives all duplicate ocurance
print('\n')

# to get unique values from a column
type(csv_data['Category'].unique())
print('______________________________________________________________________________________________')
for i in csv_data['Category'].unique():
    print(i)

to check total field if having --> App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64
to check any particular column --> 8
______________________________________________________________________________________________
______________________________________________________________________________________________
                                                   App             Category  \
164                                       Ebook Reader  BOOKS_AND_REFERENCE   
192                      Docs To Go™ Free Office Suite             BUSINESS   
193                                 Google My Business             BUSINESS   
204                                                Box             BUSINESS   
213                            

In [63]:
# dropping rows from dataframe which having NaN
csv_data.dropna()

# to fill values having NaN with some default value , since we can not remove whole data if a single column
# entry is null

fillna_csv_data = csv_data.fillna(4.5)
fillna_csv_data.isnull().sum()  #<-- sum of nan  values by each column
# we should always fill data based on column names , since every column has some different value
# so fill data based on column values
fill_rating = csv_data.fillna({'Rating': 4.5})
## above command only fills rating column , to add more columns we can add multiple dict column value pairs
print(fill_rating.isnull().sum())

## describe tells us about column details
print('_______________________________ category col description ______________________________________________')
print(csv_data['Category'].describe())

#Counting occurance of a value in table 
print('_______________ counting occurance of a value in a column _________________')
print(csv_data['Category'].value_counts().get('FAMILY', 0))

print((csv_data['Category'] == 'FAMILY').sum())

print('______________occurnace of each value in a column_______________')
for cat in csv_data['Category'].unique():
    print(cat , ":", csv_data['Category'].value_counts().get(cat, 0))

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    1
Genres            0
Last Updated      0
Current Ver       8
Android Ver       3
dtype: int64
_______________________________ category col description ______________________________________________
count      10841
unique        34
top       FAMILY
freq        1972
Name: Category, dtype: object
_______________ counting occurance of a value in a column _________________
1972
1972
______________occurnace of each value in a column_______________
ART_AND_DESIGN : 65
AUTO_AND_VEHICLES : 85
BEAUTY : 53
BOOKS_AND_REFERENCE : 231
BUSINESS : 460
COMICS : 60
COMMUNICATION : 387
DATING : 234
EDUCATION : 156
ENTERTAINMENT : 149
EVENTS : 64
FINANCE : 366
FOOD_AND_DRINK : 127
HEALTH_AND_FITNESS : 341
HOUSE_AND_HOME : 88
LIBRARIES_AND_DEMO : 85
LIFESTYLE : 382
GAME : 1144
FAMILY : 1972
MEDICAL : 463
SOCIAL : 295
SHOPPING : 2

In [15]:
csv_data.tail(5)

App             Category  \
10836                               Sya9a Maroc - FR               FAMILY   
10837               Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                         Parkinson Exercices FR              MEDICAL   
10839                  The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840  iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews                Size     Installs  Type Price  \
10836     4.5      38                 53M       5,000+  Free     0   
10837     5.0       4                3.6M         100+  Free     0   
10838     NaN       3                9.5M       1,000+  Free     0   
10839     4.5     114  Varies with device       1,000+  Free     0   
10840     4.5  398307                 19M  10,000,000+  Free     0   

      Content Rating             Genres      Last Updated         Current Ver  \
10836       Everyone          Education     July 25, 2017                1.48   
10837       Everyone          Education      July 6, 2018                 1.0   
10838       Everyone            Medical  January 20, 2017                 1.0   
10839     Mature 17+  Books & Reference  January 19, 2015  Varies with device   
10840       Everyone          Lifestyle     July 25, 2018  Varies with device   

              Android Ver  
10836          4.1 and up  
10837          4.1 and up  
10838          2.2 and up  
10839  Varies with device  
10840  Varies with device

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [66]:
d1 = pd.DataFrame([[1,2,3], [1,2,3], ['a','b','c']])
print(d1)
print('\n')
d2 = pd.DataFrame([[1,2,3], [1,2,3], ['a','b','c']],['r1', 'r2', 'r3'], ['c1','c2','c3'])
print(d2)

# each individual row or col type of a dataframe is actually a np series
print(type(d2['c1']))
print(type(d2.loc['r1']))                   # to select from row lebel use loc
print(d2.iloc[2])                           # to select row using index  
print('_________select multiple cols pass as list of cols to df_____________')
print(d2[['c1', 'c2']])       

   0  1  2
0  1  2  3
1  1  2  3
2  a  b  c


   c1 c2 c3
r1  1  2  3
r2  1  2  3
r3  a  b  c
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
c1    a
c2    b
c3    c
Name: r3, dtype: object
_________select multiple cols pass as list of cols to df_____________
   c1 c2
r1  1  2
r2  1  2
r3  a  b


In [73]:
# to   make another column with values of existing cols
print(d1[[0,1]])

d1['new_row'] = d1[0] + d1[1]

print(d1)

   0  1
0  1  2
1  1  2
2  a  b
   0  1  2 new_row
0  1  2  3       3
1  1  2  3       3
2  a  b  c      ab


## filling values with sklearn imputer

In [78]:
country_csv = pd.read_csv('rawdata\csv\country.csv')
print(country_csv)

   Country   Age   Salary Purchased
0   France  44.0  72000.0       Yes
1    Spain  27.0  48000.0       Yes
2      NaN  30.0  54000.0       NaN
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [79]:
#check isnull from above data set
country_csv.isnull().sum()

Country      1
Age          1
Salary       1
Purchased    1
dtype: int64

In [80]:
#iloc slicing - very similar to slicing 
# df.iloc[start_row : end_row, start_col : end:col]
country_csv.iloc[:,1:2]

Age
0  44.0
1  27.0
2  30.0
3  38.0
4  40.0
5  35.0
6   NaN
7  48.0
8  50.0
9  37.0

In [85]:
# updating age column from above date frame

#age
imp_mean = SimpleImputer(missing_values= np.nan, strategy= 'mean')
imp_mean.fit(country_csv.iloc[:,1:2])

#receiveing transformed values
country_csv.iloc[:,1:2] = imp_mean.transform(country_csv.iloc[:,1:2])

#salary
# now updated salary column with same mean strategy 
imp_mean.fit(country_csv.iloc[:,2:3])
country_csv.iloc[:,2:3] = imp_mean.transform(country_csv.iloc[:,2:3])

#country
# updating nan in categorical data using most frequent
imp_mostfreq = SimpleImputer(missing_values= np.nan, strategy='most_frequent')
country_csv.iloc[:,:1] = imp_mostfreq.fit_transform(country_csv.iloc[:,:1])

#purchased
# same strategy for purchased
country_csv.iloc[:,3:4] = imp_mostfreq.fit_transform(country_csv.iloc[:,3:4])
country_csv

Country        Age        Salary Purchased
0   France  44.000000  72000.000000       Yes
1    Spain  27.000000  48000.000000       Yes
2   France  30.000000  54000.000000       Yes
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [86]:
# checking if anything left as 'nan'
country_csv.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [87]:
csv_data.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [88]:
csv_data.iloc[:, 2:3] = imp_mean.fit_transform(csv_data.iloc[:, 2:3])

In [24]:
# after rating is converted with nan to mean 
# lets drop some rows these are not much weightage so we can drop
csv_data = csv_data.dropna()   #<-- drops nan rows and updates the dataframe 

print(csv_data.isnull().sum())

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64


In [90]:
# df.sample() give random samples from whole df, we shoud use instead of df.head(), df.tail() gives 5 rows
print(csv_data.sample(5))
print('______________________________df.info() gives column types  ___________________________________________')
print(csv_data.info())
print('\n')
print(country_csv.info())
print("_______________shape gives no of rows and columns __________________________")
print('no of rows and cols in country', country_csv.shape)
print('no of rows and cols in csv data dataframe ', csv_data.shape)
print('____________________df.describe()___________________________________________')
# Description: Computes summary statistics (count, mean, std, min, 25%, 50%, 75%, max) for numerical columns in DataFrame df.
print(country_csv.describe())
print(csv_data.describe())

                                                 App            Category  \
492                     eharmony - Online Dating App              DATING   
1093                  Digit Save Money Automatically             FINANCE   
9301                                      EF Academy  HEALTH_AND_FITNESS   
3392  Colorful Glitter Neon Butterfly Keyboard Theme     PERSONALIZATION   
5045  DSLR camera - Auto Focus and Blur Professional         PHOTOGRAPHY   

      Rating Reviews  Size    Installs  Type Price Content Rating  \
492      3.1   31320   53M  5,000,000+  Free     0     Mature 17+   
1093     4.5    8188   22M    100,000+  Free     0       Everyone   
9301     5.0       4   15M         50+  Free     0       Everyone   
3392     4.3    2056  9.8M    500,000+  Free     0       Everyone   
5045     3.4      30  3.0M     10,000+  Free     0       Everyone   

                Genres    Last Updated  Current Ver   Android Ver  
492             Dating   July 30, 2018        6.6.5    4.1 a

In [102]:
print(country_csv)
print(country_csv.describe())
print('________________ select col from describe dataframe___________________')
print(country_csv.describe()['Age'])
print('________________ select row from describe dataframe___________________')
print(country_csv.describe().iloc[:2,:])

   Country        Age        Salary Purchased
0   France  44.000000  72000.000000       Yes
1    Spain  27.000000  48000.000000       Yes
2   France  30.000000  54000.000000       Yes
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes
             Age        Salary
count  10.000000     10.000000
mean   38.777778  63777.777778
std     7.253777  11564.099406
min    27.000000  48000.000000
25%    35.500000  55000.000000
50%    38.388889  62388.888889
75%    43.000000  70750.000000
max    50.000000  83000.000000
________________ select col from describe dataframe___________________
count    10.000000
mean     38.777778
std       7.253777
min      27.000000
25%      35.500000
50%      38.388889
75%      43.000000
max      50

## Handling Missing Values 
delete the affected row | 
delete the affected columns  |
filling missing values ( using imputation methods )  |
advance imputation

In [26]:
print(csv_data.describe())
print('\n')
print(csv_data.describe)

             Rating
count  10829.000000
mean       4.192041
std        0.479038
min        1.000000
25%        4.100000
50%        4.200000
75%        4.500000
max        5.000000


<bound method NDFrame.describe of                                                      App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                             Parkinson Exercices F

## new data set

In [104]:
df = pd.read_csv('rawdata\csv\AB_NYC_2019.csv')
print(df.dtypes)
print('\n')
print(df.shape)

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object


(48906, 16)


In [105]:
df1 = df.copy()
print(df1.isna().sum())     #  to check which columns having empty nan values

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64


In [106]:
# here reviews per month does have int data type so we can use mean method to fill missing values
df1['reviews_per_month'].sample(10)

# first calculate the mean of column 
mean_value = df1['reviews_per_month'].mean()
df1.fillna(mean_value, inplace=True)       # be carefull while doing this command 
                                           # if column name is not specified in df the this will update whole Df
                                           # data['column_name'].fillna(data['column_name'].mean(), inplace=True)
                                           # use above

In [30]:
df1.isna().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [31]:
# interpoltae function is way to fill nan values
df2 = df.copy()
# check nan values again
print(df2.isna().sum())

# to remove nan values from reviews per month
df2['reviews_per_month'].interpolate(inplace=True)
print('\n')
print(df2.isna().sum())


id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64


id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                

C:\Users\ashpi\AppData\Local\Temp\ipykernel_16640\3031390880.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['reviews_per_month'].interpolate(inplace=True)


In [32]:
df2['last_review'].fillna('not_filled',inplace=True)
print(df2.isna().sum())
print('\n')
print(df2.sample(10))

id                                 0
name                              16
host_id                            0
host_name                         21
neighbourhood_group                0
neighbourhood                      0
latitude                           0
longitude                          0
room_type                          0
price                              0
minimum_nights                     0
number_of_reviews                  0
last_review                        0
reviews_per_month                  0
calculated_host_listings_count     0
availability_365                   0
dtype: int64


             id                                               name    host_id  \
20457  16310046    Unique Bushwick one bedroom with private garden    1451269   
16409  13175725                    Big Studio apt- Legal NY rental   65304194   
39560  30799010            Brand new building  with Manhattan view   52053537   
16255  13100305                          Spacious 1 bedroom 1 bath   

C:\Users\ashpi\AppData\Local\Temp\ipykernel_16640\1268516539.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['last_review'].fillna('not_filled',inplace=True)


In [33]:
print(df.duplicated())
# above command gives True/False values if a row is duplicated it shows 

#sums up all True values from dataframe
print(df.duplicated().sum())  

# to get rows that are duplicated pass true values
print('\n')
# keep = false --> will give all the occurance of rows which are duplicate
# keep = first(default) --> will give last occurance of dup rows will keep first with dataframe
# keep = last

print(df[df.duplicated(keep=False)])              
print('\n')
# lets drop last occurance , keep first will keep
df.drop_duplicates(keep='first', inplace=True)

print(df.duplicated().sum())
print(df.head(10))

0        False
1        False
2        False
3        False
4        False
         ...  
48901     True
48902     True
48903     True
48904     True
48905     True
Length: 48906, dtype: bool
11


         id                                              name  host_id  \
5      5099         Large Cozy 1 BR Apartment In Midtown East     7322   
6      5121                                   BlissArtsSpace!     7356   
7      5178                  Large Furnished Room Near B'way      8967   
8      5203                Cozy Clean Guest Room - Family Apt     7490   
9      5238                Cute & Cozy Lower East Side 1 bdrm     7549   
10     5295                  Beautiful 1br on Upper West Side     7702   
11     5441                   Central Manhattan/near Broadway     7989   
12     5803    Lovely Room 1, Garden, Best Area, Legal rental     9744   
13     6021  Wonderful Guest Bedroom in Manhattan for SINGLES    11528   
14     6090                     West Village Nest - Superhost  

In [34]:
# to check if any col name or set of col name having duplicates
print(df.duplicated('name').sum())
print('____________________________________________________________________________________')
print(df[df.duplicated('name', keep=False)])

998
____________________________________________________________________________________
             id                                               name    host_id  \
73        17693                    HARLEM, NEW YORK WELCOMES YOU!!      68428   
123       27883                             East Village Sanctuary     120223   
171       44096                                   Room with a View     190409   
267       64015                       Prime East Village 1 Bedroom     146944   
321       77765                               Superior @ Box House     417504   
...         ...                                                ...        ...   
48684  36382847                                       Comfort home  266211707   
48735  36412461  Sunny, Cozy, Private Room In The Heart of Bush...  147515897   
48759  36420404                                    Home Sweet Home  273656890   
48791  36427922                                Home away from home  238163900   
48826  36449743     

In [35]:
df.duplicated(['id', 'name']).sum()

# to get duplicated based on column names

np.int64(0)

## udemy  dataframes

# iteration in dataframe

In [47]:
# iteration in dataframe

# method 1 iterrows()
data = {'Item': ['Apple', 'Banana', 'Orange'],'Quantity': [10, 20, 30],'Price': [0.5, 0.3, 0.7]}
df = pd.DataFrame(data, ['a', 'b', 'c'])
print(df)
print('\n')
# Iterating over rows
for index, row in df.iterrows():
    print('index', index, 'row', row)
    # total_sales = row['Quantity'] * row['Price']
    # print(f"{row['Item']} Total Sales: ${total_sales}")

# method 2 
print('\n')
for row in df.itertuples():
    print(type(row))
    print(row)

     Item  Quantity  Price
a   Apple        10    0.5
b  Banana        20    0.3
c  Orange        30    0.7


index a row Item        Apple
Quantity       10
Price         0.5
Name: a, dtype: object
index b row Item        Banana
Quantity        20
Price          0.3
Name: b, dtype: object
index c row Item        Orange
Quantity        30
Price          0.7
Name: c, dtype: object


<class 'pandas.core.frame.Pandas'>
Pandas(Index='a', Item='Apple', Quantity=10, Price=0.5)
<class 'pandas.core.frame.Pandas'>
Pandas(Index='b', Item='Banana', Quantity=20, Price=0.3)
<class 'pandas.core.frame.Pandas'>
Pandas(Index='c', Item='Orange', Quantity=30, Price=0.7)


Using apply() - For complex row-wise transformations
The apply() method applies a function to each row or column of a DataFrame. It leverages vectorized operations, making it significantly faster than looping methods like iterrows() or itertuples(). apply() is highly versatile and optimized for performance particularly useful for complex row-wise or column-wise transformations without explicitly iterating over rows, thus saving time in large

In [49]:
data = {'Item': ['Apple', 'Banana', 'Orange'],'Quantity': [10, 20, 30],'Price': [0.5, 0.3, 0.7]}
df = pd.DataFrame(data)
# Defining a function to calculate total sales for each row
def calculate_total_sales(row):
    return f"{row['Item']} Total Sales: ${row['Quantity'] * row['Price']}"

# Applying the function row-wise
result = df.apply(calculate_total_sales, axis=1)
print('------after apply the function to each row element---------------')
print(result)
print('________________________________________________________')
for res in result:
    print(res)

------after apply the function to each row element---------------
0      Apple Total Sales: $5.0
1     Banana Total Sales: $6.0
2    Orange Total Sales: $21.0
dtype: object
________________________________________________________
Apple Total Sales: $5.0
Banana Total Sales: $6.0
Orange Total Sales: $21.0
