In [1]:
import pandas

In [2]:
! pip install pandas

You should consider upgrading via the 'C:\Users\ashpi\DataEngMain\projects\basics\pr-venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [3]:
! pip install scikit-learn

You should consider upgrading via the 'C:\Users\ashpi\DataEngMain\projects\basics\pr-venv\Scripts\python.exe -m pip install --upgrade pip' command.


## imports

In [4]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

## numpy udemy

In [13]:
# similar to range function in normal python
print(np.arange(1,11,2))                         #<-- one dimensional array
lst = [i for i in 'ashishkumar']
lst2= [i for i in 'dwivediakd1']

data = np.array([lst, lst, lst2])                #<-- passing list of list in array , will give 2-d array
print(data)                                      # two brackets

print('________________________CREATE SAMPLE NP ARRAYS_______________________________________________')
ones = np.ones((2,3))                              # takes no of rows and cols i tuple, put one argument will give 
ones_1d = np.ones(5)                               # 1d array
print(ones_1d)
print(ones)

np.random.randint(1,10,5)            # 5 is no of elements that i want to generate randomly

[1 3 5 7 9]
[['a' 's' 'h' 'i' 's' 'h' 'k' 'u' 'm' 'a' 'r']
 ['a' 's' 'h' 'i' 's' 'h' 'k' 'u' 'm' 'a' 'r']
 ['d' 'w' 'i' 'v' 'e' 'd' 'i' 'a' 'k' 'd' '1']]
________________________CREATE SAMPLE NP ARRAYS_______________________________________________
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


array([9, 6, 8, 8, 9], dtype=int32)

In [14]:
df = pd.DataFrame(data, columns=['c10', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c88', 'c9', 'c10', 'c11'])
print(df)

  c10 c2 c3 c4 c5 c6 c7 c88 c9 c10 c11
0   a  s  h  i  s  h  k   u  m   a   r
1   a  s  h  i  s  h  k   u  m   a   r
2   d  w  i  v  e  d  i   a  k   d   1


The linspace() method of the NumPy library is a useful tool to generate sequences of data points. It is also used in data visualization.
The NumPy.linspace() function returns an array of evenly spaced values within the specified interval [start, stop].

It is similar to NumPy.arange() function but instead of a step, it uses a sample number. 

In [15]:
# start , stop, no of elements
print(np.linspace(1,10,30))
# during analysis we can use generated np array to do some mathematical operation
print(np.square(np.linspace(1,10,10)))

#other ways to genarate random array between 0 to 1
print(np.random.rand(5,5))
print('\n')
print(np.random.randn(5,5))
#to get single random between low and high
print('\n')
print(np.random.randint(1,5))

# to get multiple nos between low and high
rand_int_ary = np.random.randint(1,100,20)
print(np.random.randint(1,100,10))
# for i in rand_int_ary:
#     print(i)
rand_int_ary[2]

[ 1.          1.31034483  1.62068966  1.93103448  2.24137931  2.55172414
  2.86206897  3.17241379  3.48275862  3.79310345  4.10344828  4.4137931
  4.72413793  5.03448276  5.34482759  5.65517241  5.96551724  6.27586207
  6.5862069   6.89655172  7.20689655  7.51724138  7.82758621  8.13793103
  8.44827586  8.75862069  9.06896552  9.37931034  9.68965517 10.        ]
[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]
[[0.91965284 0.48541211 0.75444517 0.46069903 0.23185077]
 [0.28809111 0.99412392 0.59423428 0.08676406 0.92007139]
 [0.86398347 0.10343525 0.89742704 0.23270419 0.70857021]
 [0.11980928 0.38323345 0.53848251 0.53498801 0.71053123]
 [0.91567971 0.70930462 0.75605011 0.65248938 0.49811726]]


[[-0.49371342 -1.22224322  1.14785215  0.26988539 -0.70051202]
 [-0.85691584  0.43761453 -0.64894703 -1.38143967 -2.6811911 ]
 [ 1.81358401 -0.00354719 -0.11861283  1.50093753  3.45789189]
 [-1.77625148  0.82410132  0.23419733  0.98061864  0.72586802]
 [ 0.63632947 -1.64690227 -0.18366174 

np.int32(56)

In [16]:
# to know the shape of an array use shape 
# shape is an attribute not function 
print('shape of rand_int_ary is :', rand_int_ary.shape)
print('shape of data array is :', data.shape)
print('max value of array is : ', rand_int_ary.max(), 'index of max value is : ',rand_int_ary.argmax())
# reshaping of array
# we can reshapre from 1d to 2d but rows * cols must be equal to no of all elements of array
print('\n')
print(rand_int_ary)
print(rand_int_ary.reshape(2,10))
print(rand_int_ary.reshape(4,5))

shape of rand_int_ary is : (20,)
shape of data array is : (3, 11)
max value of array is :  93 index of max value is :  3


[60 25 56 93 11 79 90 70 74 12 28  3 18 27 12  4 71 56 71 11]
[[60 25 56 93 11 79 90 70 74 12]
 [28  3 18 27 12  4 71 56 71 11]]
[[60 25 56 93 11]
 [79 90 70 74 12]
 [28  3 18 27 12]
 [ 4 71 56 71 11]]


In [9]:
print(pd.DataFrame(rand_int_ary))
print('\n')
print(pd.DataFrame(rand_int_ary.reshape(2,10)))
print('\n')
print(pd.DataFrame(rand_int_ary.reshape(4,5)))
print('\n')
print(pd.DataFrame(rand_int_ary.reshape(4,5), index=['a', 'b', 'c', 'd'], columns={'c1': 'A', 'c2': 'B', 'c3': 'C', 'c4': 'D', 'c5': 'E'}))

     0
0   59
1   32
2   47
3   45
4   75
5    4
6   26
7   72
8    8
9   70
10  38
11  18
12  35
13  22
14   9
15  82
16  68
17  96
18   9
19  95


    0   1   2   3   4   5   6   7  8   9
0  59  32  47  45  75   4  26  72  8  70
1  38  18  35  22   9  82  68  96  9  95


    0   1   2   3   4
0  59  32  47  45  75
1   4  26  72   8  70
2  38  18  35  22   9
3  82  68  96   9  95


   c1  c2  c3  c4  c5
a  59  32  47  45  75
b   4  26  72   8  70
c  38  18  35  22   9
d  82  68  96   9  95


In [17]:
# data = {'Name':['Tom', 'nick', 'krish', 'jack'],
#         'Age':[20, 21, 19]}
# above dict data will throw error due to mismatch or array
# --> ValueError: All arrays must be of the same length
data = [{'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19,24]},
        {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19,24]},
        {'Name':['Ashish', 'Piyush', 'AD', 'PD'],
        'Age':[20, 21, 19,24]},
        {'Namee':['Tom', 'nick', 'krish', 'jack'], #dataframe will insert NaN when any key is missing from dict of list
        'Ageee':[20, 21, 19,24]}]
df = pd.DataFrame(data)
print(df)
print('________________________________________________________________')
# data1 = {{'Name':['Tom', 'nick', 'krish', 'jack'],
#         'Age':[20, 21, 19,24]},
#         {'Name':['Tom', 'nick', 'krish', 'jack'],
#         'Age':[20, 21, 19,24]},
#         {'Name':['Ashish', 'Ramesh', 'Ram', 'AD'],
#         'Age':[20, 21, 19,24]},
#         {'Name':['Tom', 'nick', 'krish', 'jack'], 
#         'Age':[20, 21, 19,24]}}
# df = pd.DataFrame(data1)
# print(df)

                       Name               Age                     Namee  \
0  [Tom, nick, krish, jack]  [20, 21, 19, 24]                       NaN   
1  [Tom, nick, krish, jack]  [20, 21, 19, 24]                       NaN   
2  [Ashish, Piyush, AD, PD]  [20, 21, 19, 24]                       NaN   
3                       NaN               NaN  [Tom, nick, krish, jack]   

              Ageee  
0               NaN  
1               NaN  
2               NaN  
3  [20, 21, 19, 24]  
________________________________________________________________


## Reading a CSV File

In [19]:

#csv_data = pd.read_csv(r'C:\Users\ashpi\DataEngMain\projects\basics\rawdata\csv\googleplaystore.csv')

#above is full path read , below is relative path
csv_data = pd.read_csv('rawdata\csv\googleplaystore.csv')
## get top 5 data
top_10 = csv_data.head(10)

print(csv_data.columns)
print('______________________________________________________________________________________________')

# to get any column data specify the index name
print(top_10['App'])
print('length of top 10 data frame -->', len(top_10['App']))
print('______________________________________________________________________________________________')
print(len(csv_data['Rating']))

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')
______________________________________________________________________________________________
0       Photo Editor & Candy Camera & Grid & ScrapBook
1                                  Coloring book moana
2    U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                Sketch - Draw & Paint
4                Pixel Draw - Number Art Coloring Book
5                           Paper flowers instructions
6              Smoke Effect Photo Maker - Smoke Editor
7                                     Infinite Painter
8                                 Garden Coloring Book
9                        Kids Paint Free - Drawing Fun
Name: App, dtype: object
length of top 10 data frame --> 10
______________________________________________________________________________________________
10841

In [20]:
print('to check total field if having -->', csv_data.isnull().sum())

# to check if column 'current Ver' has any null values or not 
print('to check any particular column -->',csv_data['Current Ver'].isnull().sum())

# to check if any duplicates is there in any column, multiple columns can also be given
csv_data['App'].duplicated()
print(csv_data[csv_data.duplicated(keep=False)])     # keep false gives all duplicate ocurance
print('\n')

# to get unique values from a column
type(csv_data['Category'].unique())
for i in csv_data['Category'].unique():
    print(i)

to check total field if having --> App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64
to check any particular column --> 8
                                                   App             Category  \
164                                       Ebook Reader  BOOKS_AND_REFERENCE   
192                      Docs To Go™ Free Office Suite             BUSINESS   
193                                 Google My Business             BUSINESS   
204                                                Box             BUSINESS   
213                                ZOOM Cloud Meetings             BUSINESS   
...                                                ...                  ...   
8643                    Wunderlist: To-Do List & Tasks         

In [21]:
# dropping rows from dataframe which having NaN
csv_data.dropna()

# to fill values having NaN with some default value , since we can not remove whole data if a single column
# entry is null

fillna_csv_data = csv_data.fillna(4.5)
fillna_csv_data.isnull().sum()  #<-- sum of nan  values by each column
# we should always fill data based on column names , since every column has some different value
# so fill data based on column values
fill_rating = csv_data.fillna({'Rating': 4.5})
## above command only fills rating column , to add more columns we can add multiple dict column value pairs
print(fill_rating.isnull().sum())

## describe tells us about column details
print('_____________________________________________________________________________________________________')
print(csv_data['Category'].describe())

#Counting occurance of a value in table
print(csv_data['Category'].value_counts().get('FAMILY', 0))

print((csv_data['Category'] == 'FAMILY').sum())

print('______________occurnace of each value in a column_______________')
for cat in csv_data['Category'].unique():
    print(cat , ":", csv_data['Category'].value_counts().get(cat, 0))

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    1
Genres            0
Last Updated      0
Current Ver       8
Android Ver       3
dtype: int64
_____________________________________________________________________________________________________
count      10841
unique        34
top       FAMILY
freq        1972
Name: Category, dtype: object
1972
1972
______________occurnace of each value in a column_______________
ART_AND_DESIGN : 65
AUTO_AND_VEHICLES : 85
BEAUTY : 53
BOOKS_AND_REFERENCE : 231
BUSINESS : 460
COMICS : 60
COMMUNICATION : 387
DATING : 234
EDUCATION : 156
ENTERTAINMENT : 149
EVENTS : 64
FINANCE : 366
FOOD_AND_DRINK : 127
HEALTH_AND_FITNESS : 341
HOUSE_AND_HOME : 88
LIBRARIES_AND_DEMO : 85
LIFESTYLE : 382
GAME : 1144
FAMILY : 1972
MEDICAL : 463
SOCIAL : 295
SHOPPING : 260
PHOTOGRAPHY : 335
SPORTS : 384
TRAVEL_AND_LOCAL : 258
TOOLS : 843
PERSONALI

In [22]:
csv_data.tail(5)

App             Category  \
10836                               Sya9a Maroc - FR               FAMILY   
10837               Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                         Parkinson Exercices FR              MEDICAL   
10839                  The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840  iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews                Size     Installs  Type Price  \
10836     4.5      38                 53M       5,000+  Free     0   
10837     5.0       4                3.6M         100+  Free     0   
10838     NaN       3                9.5M       1,000+  Free     0   
10839     4.5     114  Varies with device       1,000+  Free     0   
10840     4.5  398307                 19M  10,000,000+  Free     0   

      Content Rating             Genres      Last Updated         Current Ver  \
10836       Everyone          Education     July 25, 2017                1.48   
10837       Everyone          Education      July 6, 2018                 1.0   
10838       Everyone            Medical  January 20, 2017                 1.0   
10839     Mature 17+  Books & Reference  January 19, 2015  Varies with device   
10840       Everyone          Lifestyle     July 25, 2018  Varies with device   

              Android Ver  
10836          4.1 and up  
10837          4.1 and up  
10838          2.2 and up  
10839  Varies with device  
10840  Varies with device

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [29]:
d1 = pd.DataFrame([[1,2,3], [1,2,3], ['a','b','c']])
print(d1)
print('\n')
d2 = pd.DataFrame([[1,2,3], [1,2,3], ['a','b','c']],['r1', 'r2', 'r3'], ['c1','c2','c3'])
print(d2)

# each individual row or col type of a dataframe is actually a np series
print(type(d2['c1']))
type(d2.loc['r1'])

   0  1  2
0  1  2  3
1  1  2  3
2  a  b  c


   c1 c2 c3
r1  1  2  3
r2  1  2  3
r3  a  b  c
<class 'pandas.core.series.Series'>


pandas.core.series.Series

## filling values with sklearn imputer

In [ ]:
country_csv = pd.read_csv('rawdata\csv\country.csv')
print(country_csv)

   Country   Age   Salary Purchased
0   France  44.0  72000.0       Yes
1    Spain  27.0  48000.0       Yes
2      NaN  30.0  54000.0       NaN
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [17]:
#check isnull from above data set
country_csv.isnull().sum()

Country      1
Age          1
Salary       1
Purchased    1
dtype: int64

In [ ]:
#iloc slicing - very similar to slicing 
# df.iloc[start_row : end_row, start_col : end:col]
country_csv.iloc[:,1:2]

Age
0  44.0
1  27.0
2  30.0
3  38.0
4  40.0
5  35.0
6   NaN
7  48.0
8  50.0
9  37.0

In [19]:
# updating age column from above date frame

imp_mean = SimpleImputer(missing_values= np.nan, strategy= 'mean')
imp_mean.fit(country_csv.iloc[:,1:2])

#receiveing transformed values
country_csv.iloc[:,1:2] = imp_mean.transform(country_csv.iloc[:,1:2])

# now updated salary column with same mean strategy 
imp_mean.fit(country_csv.iloc[:,2:3])
country_csv.iloc[:,2:3] = imp_mean.transform(country_csv.iloc[:,2:3])

# updating nan in categorical data using most frequent
imp_mostfreq = SimpleImputer(missing_values= np.nan, strategy='most_frequent')
country_csv.iloc[:,:1] = imp_mostfreq.fit_transform(country_csv.iloc[:,:1])
# same strategy for purchased
country_csv.iloc[:,3:4] = imp_mostfreq.fit_transform(country_csv.iloc[:,3:4])
country_csv

Country        Age        Salary Purchased
0   France  44.000000  72000.000000       Yes
1    Spain  27.000000  48000.000000       Yes
2   France  30.000000  54000.000000       Yes
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [20]:
country_csv.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [ ]:
csv_data.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [22]:
csv_data.iloc[:, 2:3] = imp_mean.fit_transform(csv_data.iloc[:, 2:3])

In [ ]:
# after rating is converted with nan to mean 
# lets drop some rows these are not much weightage so we can drop
csv_data = csv_data.dropna()   #<-- drops nan rows and updates the dataframe 

print(csv_data.isnull().sum())

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64


In [ ]:
# df.sample() give random samples from whole df, we shoud use instead of df.head(), df.tail() gives 5 rows
print(csv_data.sample(5))
print('______________________________df.info() gives column types  ___________________________________________')
print(csv_data.info())
print(country_csv.info())
print("_______________shape gives no of rows and columns __________________________")
print('no of rows and cols in country', country_csv.shape)
print('no of rows and cols in csv data dataframe ', csv_data.shape)
print('____________________df.describe()___________________________________________')
# Description: Computes summary statistics (count, mean, std, min, 25%, 50%, 75%, max) for numerical columns in DataFrame df.
print(country_csv.describe())
print(csv_data.describe())

                                 App       Category    Rating Reviews  \
940                           The CW  ENTERTAINMENT  4.400000  288150   
7329                     Chrome Beta   PRODUCTIVITY  4.400000  228755   
10555                      FK Jonava         SPORTS  4.193338       1   
9613   LocaToWeb - Live GPS tracking         SPORTS  4.600000     200   
695         iPair-Meet, Chat, Dating         DATING  4.500000  182986   

                     Size     Installs  Type  Price Content Rating  \
940                   21M   5,000,000+  Free      0           Teen   
7329   Varies with device  10,000,000+  Free      0       Everyone   
10555                 26M           5+  Free      0       Everyone   
9613                 3.0M       1,000+  Paid  $2.49       Everyone   
695                   77M   5,000,000+  Free      0     Mature 17+   

              Genres       Last Updated   Current Ver         Android Ver  
940    Entertainment      July 23, 2018          2.17          4

## Handling Missing Values 
delete the affected row | 
delete the affected columns  |
filling missing values ( using imputation methods )  |
advance imputation

In [45]:
print(csv_data.describe())
print('\n')
print(csv_data.describe)

             Rating
count  10829.000000
mean       4.192041
std        0.479038
min        1.000000
25%        4.100000
50%        4.200000
75%        4.500000
max        5.000000


<bound method NDFrame.describe of                                                      App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                             Parkinson Exercices F

## new data set

In [60]:
df = pd.read_csv('rawdata\csv\AB_NYC_2019.csv')
print(df.dtypes)
print('\n')
print(df.shape)

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object


(48906, 16)


In [61]:
df1 = df.copy()
print(df1.isna().sum())     #  to check which columns having empty nan values

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64


In [66]:
# here reviews per month does have int data type so we can use mean method to fill missing values
df1['reviews_per_month'].sample(10)

# first calculate the mean of column 
mean_value = df1['reviews_per_month'].mean()
df1.fillna(mean_value, inplace=True)       # be carefull while doing thsi command 
                                           # if column name is not specified in df the this will update whole Df
                                           # data['column_name'].fillna(data['column_name'].mean(), inplace=True)
                                           # use above

In [65]:
df1.isna().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [76]:
# interpoltae function is way to fill nan values
df2 = df.copy()
# check nan values again
print(df2.isna().sum())

# to remove nan values from reviews per month
df2['reviews_per_month'].interpolate(inplace=True)
print('\n')
print(df2.isna().sum())


id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64


id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                

C:\Users\ashpi\AppData\Local\Temp\ipykernel_9496\3031390880.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['reviews_per_month'].interpolate(inplace=True)


In [78]:
df2['last_review'].fillna('not_filled',inplace=True)
print(df2.isna().sum())
print('\n')
print(df2.sample(10))

id                                 0
name                              16
host_id                            0
host_name                         21
neighbourhood_group                0
neighbourhood                      0
latitude                           0
longitude                          0
room_type                          0
price                              0
minimum_nights                     0
number_of_reviews                  0
last_review                        0
reviews_per_month                  0
calculated_host_listings_count     0
availability_365                   0
dtype: int64


             id                                               name    host_id  \
19451  15517755           Huge Bedroom w/direct access to backyard   30047867   
7769    5891777                  Cozy 1BD side apartment w/parking   18014128   
48763  36421390                     House feeling in Caroll Garden    3827238   
16743  13379511                Charming Brownstone in Clinton Hill   

C:\Users\ashpi\AppData\Local\Temp\ipykernel_9496\1268516539.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['last_review'].fillna('not_filled',inplace=True)


In [87]:
print(df.duplicated())
# above command gives True/False values if a row is duplicated it shows 

#sums up all True values from dataframe
print(df.duplicated().sum())  

# to get rows that are duplicated pass true values
print('\n')
# keep = false --> will give all the occurance of rows which are duplicate
# keep = first(default) --> will give last occurance of dup rows will keep first with dataframe
# keep = last

print(df[df.duplicated(keep=False)])              
print('\n')
# lets drop last occurance , keep first will keep
df.drop_duplicates(keep='first', inplace=True)

print(df.duplicated().sum())
print(df.head(10))

0        False
1        False
2        False
3        False
4        False
         ...  
48890    False
48891    False
48892    False
48893    False
48894    False
Length: 48895, dtype: bool
0


Empty DataFrame
Columns: [id, name, host_id, host_name, neighbourhood_group, neighbourhood, latitude, longitude, room_type, price, minimum_nights, number_of_reviews, last_review, reviews_per_month, calculated_host_listings_count, availability_365]
Index: []


0
     id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   
5  5099         Large Cozy 1 BR Apartment In Midtown East     7322   
6  5121                                   BlissArtsS

In [98]:
# to check if any col name or set of col name having duplicates
print(df.duplicated('name').sum())
print('____________________________________________________________________________________')
print(df[df.duplicated('name', keep=False)])

998
____________________________________________________________________________________
             id                                               name    host_id  \
73        17693                    HARLEM, NEW YORK WELCOMES YOU!!      68428   
123       27883                             East Village Sanctuary     120223   
171       44096                                   Room with a View     190409   
267       64015                       Prime East Village 1 Bedroom     146944   
321       77765                               Superior @ Box House     417504   
...         ...                                                ...        ...   
48684  36382847                                       Comfort home  266211707   
48735  36412461  Sunny, Cozy, Private Room In The Heart of Bush...  147515897   
48759  36420404                                    Home Sweet Home  273656890   
48791  36427922                                Home away from home  238163900   
48826  36449743     

In [103]:
df.duplicated(['id', 'name']).sum()

# to get duplicated based on column names

np.int64(0)

## handling outliers